
name: Insight Engine
short: IE-ETL
description: ETL Data loading
edit:
  text: Edit this page
  url: https://gitlab.com/i-360/dataops/insightengineetl/-/edit/master/
  map:
    index.mdx: README.md
search: true
footer:
  links:
    - text: Gitlab
      url: https://gitlab.com/i-360/dataops/insightengineetl
    - text: Company
      url: https://www.i-360.com
    - text: MGen
      url: https://github.com/lancetipton/mgen
  year: true
  text: © Copyright
header:
theme:
  colors:
    primary: '#32a852'
    info: '#32a852'
  logo:
    background: '#32a852'
pages:
  ignore:
    - setup
  hidden:
    - imd


