env:
  NODE_ENV: local
  MG_BASE_PATH: /
  MG_API_PORT: 8080
  MG_API_URL: http://localhost
  # If set will build a static version of mgen and include all site markdown files
  MG_STATIC_BUILD: 0

  # Path to folder containing sites to be built when doing a static site build
  MG_STATIC_SITES: 
